name: Release

on:
  release:

jobs:
  apk:
    name: Release APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
    - run: flutter pub get
    - run: flutter build apk --no-sound-null-safety #package:bluetoothadapter doesn't support null safety
    - run: cd build/app/outputs && tree
    - run: |
        cd build/app/outputs/flutter-apk/
        mv app.apk blueshot.apk || true
        mv app.apk.sha1 hashblue.apk.sha1 || true
        mv app-release.apk blue-release.apk || true
        mv app-debug.apk blue-bug.apk || true
        ls -al
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUBTOKEN }}
        file: build/app/outputs/flutter-apk/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
